package(default_visibility = ["//visibility:public"])

licenses(["notice"])

cc_binary(
    name = 'http_server',
    srcs = [
      'http_server.cc',
    ],
    deps = [
      '//third_party/pistache:pistache',
    ],
)

