licenses(["notice"])
package(default_visibility = ["//visibility:public"])

cc_binary(
  name = "str_join",
  #deps = ["//third_party/absl:absl"],
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["str_join.cc"],
)
